language: php
php:
  - "5.6"

sudo: false

services: mysql

install:
  - composer self-update
  - composer install --dev --no-interaction

before_script:
  # Database
  - mysql -e 'create database brewblogger;'
  - mysql -u root -e "CREATE USER 'brewblogger'@'localhost' IDENTIFIED BY 'brewblogger'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'brewblogger'@'localhost' WITH GRANT OPTION;"
  - mysql -u root brewblogger < sql/3.0.0_new_install.sql
  - mysql -u root brewblogger -e 'UPDATE preferences SET mode=2;'

  # Update Behat Path

  # Start up the server
  - php -S localhost:8000 &
  - sleep 3

script:
  - vendor/bin/behat
#  - php vendor/bin/phpunit -c phpunit.xml.dist
